version: '3'

services:


  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

  web:
    build: .
    container_name: fastapi_app
    volumes:
      - .:/src
    ports:
      - "8001:8001"
    depends_on:
      - db
